npx svelte-migrate sveltekit-2
- I had to clean npm cache
- then, npm run build was KO...
TypeError [Error]: (intermediate value).globEager is not a function
- this is because Vite v5 changed globEager -> glob(.., {eager:true}) --> OK!
- all tests are OK